export const CATEGORIES = [
  { value: 'tech & saas', label: ' Tech & SaaS' },
  { value: 'ai & machine learning', label: 'AI & Machine Learning' },
  { value: 'e-commerce & retail', label: ' E-commerce & Retail' },
  { value: 'health & wellness', label: ' Health & Wellness' },
  { value: 'creative & design', label: ' Creative & Design' },
  { value: 'creator & influencer', label: 'Creator & Influencer' },
  { value: 'games & entertainment', label: ' Games & Entertainment' },
  { value: 'finance & fintech', label: 'Finance & Fintech' },
  { value: 'web3 & blockchain', label: 'Web3 & Blockchain' },
  { value: 'food & beverage', label: ' Food & Beverage' },
  { value: 'travel & hospitality', label: ' Travel & Hospitality' },
  { value: 'education & e-learning', label: ' Education & E-learning' },
  { value: 'professional services', label: ' Professional Services' },
  { value: 'real estate & proptech', label: 'Real Estate & PropTech' },
]; 